# -*- coding: utf-8 -*-
"""translate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOgtlrZx7Jk1igf9O13AuIyuJjAhFGKW
"""

import json

# Define the path to the JSON file
file_path = '/content/drug_data_grouped.json'

# Load the JSON file into a Python object
with open(file_path, 'r', encoding='utf-8') as f:
    drug_data = json.load(f)

# Print the number of entries loaded from the JSON file
print(f"Number of entries loaded: {len(drug_data)}")

# If the drug_data is not empty, print the first entry in a pretty-printed format
if drug_data:
    print("\nFirst entry of drug_data:")
    print(json.dumps(drug_data[0], indent=2, ensure_ascii=False))

from transformers import pipeline

# Initialize the translation pipeline
translator = pipeline(
    'translation',
    model='facebook/nllb-200-distilled-600M',
    src_lang='spa_Latn',
    tgt_lang='vie_Latn'
)

print("Translation model initialized successfully for Spanish to Vietnamese.")

translated_drug_data = []

# Define the fields to be translated
translation_fields = ['tên thuốc', 'tên y sinh', 'mô tả']

print(f"Starting translation of fields: {translation_fields}")

# Iterate through each drug entry
for i, entry in enumerate(drug_data):
    # Create a copy to store translated data or modify in place
    translated_entry = entry.copy()

    for field in translation_fields:
        if field in translated_entry and translated_entry[field]:
            # Ensure the text is a list for the translator and handle potential empty strings
            text_to_translate = translated_entry[field]
            if isinstance(text_to_translate, str) and text_to_translate.strip():
                # The translator expects a list of strings, even for a single item
                translated_text_list = translator([text_to_translate], max_length=1024)
                # Extract the translated text from the result list
                translated_entry[field] = translated_text_list[0]['translation_text']
            else:
                # If the field is empty or not a valid string, keep it as is or set to empty string
                translated_entry[field] = translated_entry[field] # or ''

    translated_drug_data.append(translated_entry)

    if (i + 1) % 100 == 0: # Print progress every 100 entries
        print(f"Translated {i + 1}/{len(drug_data)} entries...")

print("Translation process completed.")

# Display the first translated entry to verify
if translated_drug_data:
    print("\nFirst translated entry:")
    print(json.dumps(translated_drug_data[0], indent=2, ensure_ascii=False))
else:
    print("No data to display after translation.")

import json

# Define the output file path
output_file_path = 'drug_data_grouped_translated.json'

# Save the translated drug data to a new JSON file
with open(output_file_path, 'w', encoding='utf-8') as f:
    json.dump(translated_drug_data, f, indent=2, ensure_ascii=False)

print(f"Translated data saved to '{output_file_path}'")