# -*- coding: utf-8 -*-
"""RAG_embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gb9b3wFZrp2Al4JQh9_KzRZxIBQ9RERX
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q torch transformers peft accelerate pandas faiss-cpu sentence-transformers langchain langchain-community

"""# **RAG trên toàn bộ tập dữu liệu bao gồm cả file dữ liệu đúng và sai**"""

import pandas as pd
import json
import os
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
# --- SỬA LỖI IMPORT TẠI ĐÂY ---
from langchain_core.documents import Document

# ================= 1. CẤU HÌNH ĐƯỜNG DẪN =================
# Đường dẫn đến file chứa toàn dữ liệu ĐÚNG
TRAIN_TRUE_PATH = "/content/drive/MyDrive/KPDLHLV/Data/checkpoint_results.jsonl"

# Đường dẫn đến file chứa toàn dữ liệu SAI
TRAIN_FALSE_PATH = "/content/drive/MyDrive/KPDLHLV/Data/checkpoint_results_sai.jsonl"

# Model Embedding
EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# ================= 2. HÀM LOAD DỮ LIỆU =================
def load_data_to_docs(file_paths):
    docs = []
    total_loaded = 0

    for path in file_paths:
        if not os.path.exists(path):
            print(f"⚠️ Cảnh báo: Không tìm thấy file {path}, bỏ qua.")
            continue

        print(f"📂 Đang đọc file: {path}...")
        count = 0
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    line = line.strip()
                    if not line: continue

                    item = json.loads(line)

                    context = item.get('context', '')
                    statement = item.get('statement', '')
                    answer = item.get('answer', '')

                    if not answer:
                        if "sai" in path.lower(): answer = "Sai"
                        else: answer = "Đúng"

                    # Nội dung để Embedding (Tìm kiếm)
                    content_for_search = f"Ngữ cảnh: {context}\nMệnh đề: {statement}"

                    # Metadata (Thông tin gốc)
                    metadata = {
                        "original_context": context,
                        "original_statement": statement,
                        "answer": answer
                    }

                    docs.append(Document(page_content=content_for_search, metadata=metadata))
                    count += 1
                except Exception as e:
                    continue

        print(f"   -> Đã lấy {count} mẫu từ file này.")
        total_loaded += count

    print(f"✅ TỔNG CỘNG: Đã nạp {total_loaded} mẫu dữ liệu vào bộ nhớ.")
    return docs

# ================= 3. THỰC THI =================

# Danh sách các file cần load
list_files = [TRAIN_TRUE_PATH, TRAIN_FALSE_PATH]

# Load dữ liệu
documents = load_data_to_docs(list_files)

if len(documents) > 0:
    print("\n🚀 Đang tạo Embedding và Index vào FAISS...")
    print("⏳ Quá trình này có thể mất vài phút...")

    # Load model embedding
    embedding_model = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={'device': 'cuda'} # Chạy trên GPU
    )

    # Tạo Vector Database
    db = FAISS.from_documents(documents, embedding_model)

    print("✅ Đã xây xong RAG Database thành công!")
else:
    print("❌ Lỗi: Không load được dữ liệu nào.")

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel
from tqdm import tqdm

# ================= CẤU HÌNH MODEL FINETUNE =================
ADAPTER_PATH = "/content/drive/MyDrive/KPDLHLV/qwen3_slm_batch6/checkpoint-3800"
BASE_MODEL_ID = "Qwen/Qwen3-0.6B" # (Thực ra là Qwen2.5-0.5B hoặc Qwen2-0.5B, bạn check lại đúng tên nhé)

TEST_FILE = "/content/drive/MyDrive/KPDLHLV/Data/data_test_normalize.csv"
OUTPUT_FILE = "/content/drive/MyDrive/KPDLHLV/Data/Result_RAG_Finetune.xlsx"
DEVICE = "cuda"

# ================= LOAD QWEN MODEL =================
print("📦 Đang load Qwen Finetuned Model...")
tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH, trust_remote_code=True)
if tokenizer.pad_token is None: tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    device_map=DEVICE,
    torch_dtype=torch.float16,
    trust_remote_code=True
)
base_model.resize_token_embeddings(len(tokenizer))

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()
print("✅ Qwen đã sẵn sàng!")

# ================= HÀM RAG QUERY =================
def generate_rag_prompt(query_context, query_statement, k=3):
    """
    Hàm này tìm 3 ví dụ tương tự nhất trong dữ liệu train
    để làm 'gợi ý' cho model.
    """
    query_text = f"Ngữ cảnh: {query_context}\nMệnh đề: {query_statement}"

    # 1. Tìm kiếm trong FAISS
    # k=3: Lấy 3 ví dụ giống nhất
    docs_and_scores = db.similarity_search_with_score(query_text, k=k)

    examples_text = ""
    for doc, score in docs_and_scores:
        # Chỉ lấy những ví dụ thực sự liên quan (score thấp là giống, tùy metric, faiss L2 thì thấp là tốt)
        # Ở đây mình cứ lấy hết top k
        ex_ctx = doc.metadata['original_context']
        ex_stmt = doc.metadata['original_statement']
        ex_ans = doc.metadata['answer']

        examples_text += f"---\nVí dụ tham khảo:\nNgữ cảnh: {ex_ctx}\nMệnh đề: {ex_stmt}\n=> Đáp án chuẩn: {ex_ans}\n"

    # 2. Ghép vào Prompt cuối cùng
    final_prompt = f"""Dưới đây là một số ví dụ tương tự từ cơ sở dữ liệu để bạn tham khảo:
{examples_text}
---
Dựa vào kiến thức của bạn và các ví dụ trên, hãy trả lời câu hỏi sau:
Ngữ cảnh: {query_context}
Mệnh đề: {query_statement}
Hãy phân loại mệnh đề trên là 'Đúng' hoặc 'Sai'. Chỉ trả lời đúng một từ: Đúng hoặc Sai.
Câu trả lời:"""
    return final_prompt

# ================= CHẠY TRÊN FILE TEST =================
print(f"📂 Đang đọc file Test: {TEST_FILE}")
if TEST_FILE.endswith('.csv'):
    df = pd.read_csv(TEST_FILE)
else:
    df = pd.read_excel(TEST_FILE)

results = []
print("▶️ Bắt đầu chạy RAG Inference...")

for idx, row in tqdm(df.iterrows(), total=len(df)):
    # Lấy dữ liệu test
    ctx = str(row.get('context', '')) if pd.notna(row.get('context')) else ""
    stmt = str(row.get('statement', ''))

    # 1. Tạo RAG Prompt (Có kèm ví dụ)
    rag_prompt = generate_rag_prompt(ctx, stmt, k=2) # Lấy 2 ví dụ tương tự nhất

    # 2. Tokenize & Generate
    inputs = tokenizer(rag_prompt, return_tensors="pt").to(DEVICE)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=5,
            temperature=0.01, # Nhiệt độ thấp để ổn định
            pad_token_id=tokenizer.pad_token_id
        )

    # 3. Decode
    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Cắt lấy phần trả lời cuối cùng
    answer = full_response.split("Câu trả lời:")[-1].strip()

    # Chuẩn hóa đầu ra
    final_decision = "Sai"
    if "đúng" in answer.lower(): final_decision = "Đúng"
    elif "sai" in answer.lower(): final_decision = "Sai"

    results.append({
        "Context": ctx,
        "Statement": stmt,
        "Prediction": final_decision,
        "Raw_Response": answer # Lưu để debug xem nó trả lời gì
    })

# Lưu kết quả
pd.DataFrame(results).to_excel(OUTPUT_FILE, index=False)
print(f"✅ Xong! Kết quả lưu tại {OUTPUT_FILE}")

"""# **RAG trên toàn bộ tập dữu liệu bao gồm cả file dữ liệu đúng**"""

import pandas as pd
import json
import os
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
# Import chuẩn mới nhất
from langchain_core.documents import Document

# ================= 1. CẤU HÌNH ĐƯỜNG DẪN =================
# CHỈ DÙNG FILE DỮ LIỆU ĐÚNG (Dữ liệu chuẩn)
TRAIN_TRUE_PATH = "/content/drive/MyDrive/KPDLHLV/Data/checkpoint_results.jsonl"

# Model Embedding
EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# ================= 2. HÀM LOAD DỮ LIỆU =================
def load_true_data(file_path):
    docs = []

    if not os.path.exists(file_path):
        print(f"❌ Lỗi: Không tìm thấy file {file_path}")
        return []

    print(f"📂 Đang đọc 'Kho tri thức chuẩn' từ: {file_path}...")
    count = 0
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                line = line.strip()
                if not line: continue

                item = json.loads(line)

                # Chỉ lấy những mẫu có nhãn là "Đúng" (hoặc True)
                # Tuy nhiên, vì file này bạn bảo là file toàn đúng, nên ta cứ lấy hết.
                # Nếu file lẫn lộn thì thêm if item['answer'] == 'Đúng': ...

                context = item.get('context', '')
                statement = item.get('statement', '')
                answer = "Đúng" # Vì đây là file chuẩn

                # Nội dung để Embedding
                content_for_search = f"Ngữ cảnh: {context}\nMệnh đề: {statement}"

                # Metadata
                metadata = {
                    "original_context": context,
                    "original_statement": statement,
                    "answer": answer
                }

                docs.append(Document(page_content=content_for_search, metadata=metadata))
                count += 1
            except Exception as e:
                continue

    print(f"✅ Đã nạp {count} kiến thức chuẩn vào bộ nhớ.")
    return docs

# ================= 3. THỰC THI =================

# Load dữ liệu
documents = load_true_data(TRAIN_TRUE_PATH)

if len(documents) > 0:
    print("\n🚀 Đang tạo Embedding và Index vào FAISS...")
    print("⏳ Quá trình này có thể mất vài phút...")

    # Load model embedding
    embedding_model = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={'device': 'cuda'}
    )

    # Tạo Vector Database
    db = FAISS.from_documents(documents, embedding_model)

    print("✅ Đã xây xong RAG Database (Clean Version) thành công!")
else:
    print("❌ Không có dữ liệu để tạo DB.")

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel
from tqdm import tqdm

# ================= CẤU HÌNH MODEL FINETUNE =================
ADAPTER_PATH = "/content/drive/MyDrive/KPDLHLV/qwen3_slm_batch6/checkpoint-3800"
BASE_MODEL_ID = "Qwen/Qwen3-0.6B" # (Thực ra là Qwen2.5-0.5B hoặc Qwen2-0.5B, bạn check lại đúng tên nhé)

TEST_FILE = "/content/drive/MyDrive/KPDLHLV/Data/data_test_normalize.csv"
OUTPUT_FILE = "/content/drive/MyDrive/KPDLHLV/Data/Result_RAG_Finetune.xlsx"
DEVICE = "cuda"

# ================= LOAD QWEN MODEL =================
print("📦 Đang load Qwen Finetuned Model...")
tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH, trust_remote_code=True)
if tokenizer.pad_token is None: tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    device_map=DEVICE,
    torch_dtype=torch.float16,
    trust_remote_code=True
)
base_model.resize_token_embeddings(len(tokenizer))

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()
print("✅ Qwen đã sẵn sàng!")

# ================= HÀM RAG QUERY =================
def generate_rag_prompt(query_context, query_statement, k=3):
    """
    Hàm này tìm 3 ví dụ tương tự nhất trong dữ liệu train
    để làm 'gợi ý' cho model.
    """
    query_text = f"Ngữ cảnh: {query_context}\nMệnh đề: {query_statement}"

    # 1. Tìm kiếm trong FAISS
    # k=3: Lấy 3 ví dụ giống nhất
    docs_and_scores = db.similarity_search_with_score(query_text, k=k)

    examples_text = ""
    for doc, score in docs_and_scores:
        # Chỉ lấy những ví dụ thực sự liên quan (score thấp là giống, tùy metric, faiss L2 thì thấp là tốt)
        # Ở đây mình cứ lấy hết top k
        ex_ctx = doc.metadata['original_context']
        ex_stmt = doc.metadata['original_statement']
        ex_ans = doc.metadata['answer']

        examples_text += f"---\nVí dụ tham khảo:\nNgữ cảnh: {ex_ctx}\nMệnh đề: {ex_stmt}\n=> Đáp án chuẩn: {ex_ans}\n"

    # 2. Ghép vào Prompt cuối cùng
    final_prompt = f"""Dưới đây là một số ví dụ tương tự từ cơ sở dữ liệu để bạn tham khảo:
{examples_text}
---
Dựa vào kiến thức của bạn và các ví dụ trên, hãy trả lời câu hỏi sau:
Ngữ cảnh: {query_context}
Mệnh đề: {query_statement}
Hãy phân loại mệnh đề trên là 'Đúng' hoặc 'Sai'. Chỉ trả lời đúng một từ: Đúng hoặc Sai.
Câu trả lời:"""
    return final_prompt

# ================= CHẠY TRÊN FILE TEST =================
print(f"📂 Đang đọc file Test: {TEST_FILE}")
if TEST_FILE.endswith('.csv'):
    df = pd.read_csv(TEST_FILE)
else:
    df = pd.read_excel(TEST_FILE)

results = []
print("▶️ Bắt đầu chạy RAG Inference...")

for idx, row in tqdm(df.iterrows(), total=len(df)):
    # Lấy dữ liệu test
    ctx = str(row.get('context', '')) if pd.notna(row.get('context')) else ""
    stmt = str(row.get('statement', ''))

    # 1. Tạo RAG Prompt (Có kèm ví dụ)
    rag_prompt = generate_rag_prompt(ctx, stmt, k=2) # Lấy 2 ví dụ tương tự nhất

    # 2. Tokenize & Generate
    inputs = tokenizer(rag_prompt, return_tensors="pt").to(DEVICE)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=5,
            temperature=0.01, # Nhiệt độ thấp để ổn định
            pad_token_id=tokenizer.pad_token_id
        )

    # 3. Decode
    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Cắt lấy phần trả lời cuối cùng
    answer = full_response.split("Câu trả lời:")[-1].strip()

    # Chuẩn hóa đầu ra
    final_decision = "Sai"
    if "đúng" in answer.lower(): final_decision = "Đúng"
    elif "sai" in answer.lower(): final_decision = "Sai"

    results.append({
        "Context": ctx,
        "Statement": stmt,
        "Prediction": final_decision,
        "Raw_Response": answer # Lưu để debug xem nó trả lời gì
    })

# Lưu kết quả
pd.DataFrame(results).to_excel(OUTPUT_FILE, index=False)
print(f"✅ Xong! Kết quả lưu tại {OUTPUT_FILE}")

"""# **RAG trên toàn bộ tập dữu liệu bao gồm cả file dữ liệu đúng với mô hình Qwen gốc**"""

import pandas as pd
import json
import os
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
# Import chuẩn mới nhất
from langchain_core.documents import Document

# ================= 1. CẤU HÌNH ĐƯỜNG DẪN =================
# CHỈ DÙNG FILE DỮ LIỆU ĐÚNG (Dữ liệu chuẩn)
TRAIN_TRUE_PATH = "/content/drive/MyDrive/KPDLHLV/Data/checkpoint_results.jsonl"

# Model Embedding
EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# ================= 2. HÀM LOAD DỮ LIỆU =================
def load_true_data(file_path):
    docs = []

    if not os.path.exists(file_path):
        print(f"❌ Lỗi: Không tìm thấy file {file_path}")
        return []

    print(f"📂 Đang đọc 'Kho tri thức chuẩn' từ: {file_path}...")
    count = 0
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                line = line.strip()
                if not line: continue

                item = json.loads(line)

                # Chỉ lấy những mẫu có nhãn là "Đúng" (hoặc True)
                # Tuy nhiên, vì file này bạn bảo là file toàn đúng, nên ta cứ lấy hết.
                # Nếu file lẫn lộn thì thêm if item['answer'] == 'Đúng': ...

                context = item.get('context', '')
                statement = item.get('statement', '')
                answer = "Đúng" # Vì đây là file chuẩn

                # Nội dung để Embedding
                content_for_search = f"Ngữ cảnh: {context}\nMệnh đề: {statement}"

                # Metadata
                metadata = {
                    "original_context": context,
                    "original_statement": statement,
                    "answer": answer
                }

                docs.append(Document(page_content=content_for_search, metadata=metadata))
                count += 1
            except Exception as e:
                continue

    print(f"✅ Đã nạp {count} kiến thức chuẩn vào bộ nhớ.")
    return docs

# ================= 3. THỰC THI =================

# Load dữ liệu
documents = load_true_data(TRAIN_TRUE_PATH)

if len(documents) > 0:
    print("\n🚀 Đang tạo Embedding và Index vào FAISS...")
    print("⏳ Quá trình này có thể mất vài phút...")

    # Load model embedding
    embedding_model = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={'device': 'cuda'}
    )

    # Tạo Vector Database
    db = FAISS.from_documents(documents, embedding_model)

    print("✅ Đã xây xong RAG Database (Clean Version) thành công!")
else:
    print("❌ Không có dữ liệu để tạo DB.")

import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm

# ================= 1. CẤU HÌNH (DÙNG ĐÚNG MODEL BẠN YÊU CẦU) =================
BASE_MODEL_ID = "Qwen/Qwen3-0.6B" # <-- Đã đổi về model bạn muốn

TEST_FILE = "/content/drive/MyDrive/KPDLHLV/Data/data_test_normalize.csv"
OUTPUT_FILE = "/content/drive/MyDrive/KPDLHLV/Data/Result_RAG_Base_Model_Qwen3.xlsx"
DEVICE = "cuda"

# ================= 2. LOAD MODEL =================
print(f"📦 Đang load Base Model: {BASE_MODEL_ID}...")

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, trust_remote_code=True)
if tokenizer.pad_token is None: tokenizer.pad_token = tokenizer.eos_token

# Load Model
model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    device_map=DEVICE,
    torch_dtype=torch.float16,
    trust_remote_code=True
)
model.eval()
print("✅ Base Model đã sẵn sàng!")

# ================= 3. HÀM RAG QUERY (TỐI ƯU CHO BASE MODEL) =================
def generate_rag_prompt(query_context, query_statement, k=3):
    query_text = f"Ngữ cảnh: {query_context}\nMệnh đề: {query_statement}"

    # 1. Tìm thông tin trong Vector DB (Biến 'db' từ bước trước)
    docs_and_scores = db.similarity_search_with_score(query_text, k=k)

    # 2. Xây dựng ngữ cảnh tham khảo (Context)
    knowledge_text = ""
    for i, (doc, score) in enumerate(docs_and_scores, 1):
        ex_ctx = doc.metadata['original_context']
        ex_stmt = doc.metadata['original_statement']
        # Trình bày dưới dạng sự thật (Fact)
        knowledge_text += f"Sự thật {i}: {ex_ctx} {ex_stmt} (Là thông tin Chính xác).\n"

    # 3. PROMPT DẠNG HOÀN THÀNH CÂU (Completion)
    # Base model rất giỏi việc điền tiếp. Ta đưa cho nó dữ kiện và bắt nó điền kết luận.
    final_prompt = f"""Dựa vào các sự thật y khoa sau đây:
{knowledge_text}
---
Dựa trên các sự thật trên, hãy kiểm tra mệnh đề sau:
Ngữ cảnh: {query_context}
Mệnh đề: {query_statement}

Câu hỏi: Mệnh đề trên là Đúng hay Sai?
Đáp án (chỉ ghi Đúng hoặc Sai):"""
    return final_prompt

# ================= 4. CHẠY INFERENCE =================
print(f"📂 Đang đọc file Test: {TEST_FILE}")
try:
    if TEST_FILE.endswith('.csv'):
        df = pd.read_csv(TEST_FILE)
    else:
        df = pd.read_excel(TEST_FILE)
except Exception as e:
    print(f"❌ Lỗi đọc file: {e}")
    df = pd.DataFrame()

if not df.empty:
    results = []
    print("▶️ Bắt đầu chạy Inference...")

    for idx, row in tqdm(df.iterrows(), total=len(df)):
        ctx = str(row.get('context', '')) if pd.notna(row.get('context')) else ""
        stmt = str(row.get('statement', ''))

        try:
            rag_prompt = generate_rag_prompt(ctx, stmt, k=3)
        except NameError:
            print("❌ Lỗi: Chưa có biến 'db'. Hãy chạy cell tạo Vector DB trước!")
            break

        # Tokenize & Generate
        inputs = tokenizer(rag_prompt, return_tensors="pt").to(DEVICE)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=3, # Chỉ cần 2-3 token là đủ cho chữ "Đúng"/"Sai"
                temperature=0.01, # Nhiệt độ cực thấp để model không "sáng tạo" linh tinh
                pad_token_id=tokenizer.pad_token_id
            )

        # Decode
        full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
        # Cắt lấy phần model vừa điền vào sau dấu hai chấm
        answer = full_response.split("Đáp án (chỉ ghi Đúng hoặc Sai):")[-1].strip()

        # Chuẩn hóa
        final_decision = "Sai"
        if "đúng" in answer.lower(): final_decision = "Đúng"
        elif "sai" in answer.lower(): final_decision = "Sai"

        results.append({
            "Context": ctx,
            "Statement": stmt,
            "Prediction": final_decision,
            "Raw_Response": answer
        })

    # Lưu kết quả
    if results:
        pd.DataFrame(results).to_excel(OUTPUT_FILE, index=False)
        print(f"\n✅ Xong! Kết quả Base Model (Qwen3) lưu tại {OUTPUT_FILE}")

"""# **RAG trên bộ dữ liệu đúng và VimedAQA với mô hình Qwen đã finetune**"""

!pip install -q datasets

from datasets import load_dataset
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

# 1. Load Dataset từ HuggingFace
print("📥 Đang tải dataset tmnam20/ViMedAQA...")
dataset = load_dataset("tmnam20/ViMedAQA", split="train")

# 2. Tiền xử lý: Chuyển đổi QA thành Document Context
print("🔄 Đang xử lý dữ liệu...")
knowledge_docs = []

for item in dataset:
    # Lấy câu hỏi và câu trả lời
    q = item.get('question', '')
    a = item.get('answer', '')

    # Gộp lại thành một đoạn kiến thức (Context)
    # Format này giúp embedding model hiểu ngữ nghĩa trọn vẹn
    content = f"Câu hỏi y tế: {q}\nThông tin giải đáp: {a}"

    # Metadata lưu nguồn
    metadata = {"source": "ViMedAQA", "type": "knowledge"}

    knowledge_docs.append(Document(page_content=content, metadata=metadata))

print(f"✅ Đã xử lý {len(knowledge_docs)} mẫu kiến thức từ ViMedAQA.")

# 3. Tạo Vector DB cho Kiến thức (Knowledge Index)
# Lưu ý: Dùng chung model embedding với phần trước để đồng bộ
EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

print("🚀 Đang tạo Knowledge Index (FAISS)...")
embedding_model = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL_NAME,
    model_kwargs={'device': 'cuda'}
)

knowledge_db = FAISS.from_documents(knowledge_docs, embedding_model)
print("✅ Đã tạo xong Knowledge Database (từ ViMedAQA)!")

import json
import os
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS

# 1. Cấu hình đường dẫn (Chỉ file ĐÚNG)
TRAIN_TRUE_PATH = "/content/drive/MyDrive/KPDLHLV/Data/checkpoint_results.jsonl"

def load_true_only_data(file_path):
    docs = []

    if not os.path.exists(file_path):
        print(f"❌ Lỗi: Không tìm thấy file {file_path}")
        return []

    print(f"📂 Đang đọc dữ liệu ví dụ từ: {file_path}...")
    count = 0
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                line = line.strip()
                if not line: continue
                item = json.loads(line)

                context = item.get('context', '')
                statement = item.get('statement', '')
                # Mặc định là Đúng vì bạn chỉ load file đúng
                answer = item.get('answer', 'Đúng')

                # Nội dung để tìm kiếm (Statement là chính)
                content_for_search = f"Mệnh đề: {statement}"

                # Metadata đầy đủ
                metadata = {
                    "original_context": context,
                    "original_statement": statement,
                    "answer": answer,
                    "type": "example"
                }

                docs.append(Document(page_content=content_for_search, metadata=metadata))
                count += 1
            except:
                continue

    print(f"✅ Đã nạp {count} ví dụ mẫu (nhãn Đúng).")
    return docs

# 2. Tạo Vector DB (biến 'db')
# Lưu ý: Biến 'embedding_model' đã được tạo ở cell ViMedAQA trước đó
if 'embedding_model' not in globals():
    print("⚠️ Cảnh báo: Chưa có biến embedding_model. Hãy chạy cell ViMedAQA trước!")
else:
    print("🚀 Đang tạo Index cho ví dụ mẫu...")
    example_docs = load_true_only_data(TRAIN_TRUE_PATH)

    if len(example_docs) > 0:
        db = FAISS.from_documents(example_docs, embedding_model)
        print("✅ Đã tạo xong kho ví dụ mẫu 'db' (Chỉ chứa dữ liệu Đúng)!")
    else:
        print("❌ Không có dữ liệu để tạo DB.")

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel
import gc

# ================= 1. CẤU HÌNH ĐƯỜNG DẪN =================
# Đường dẫn đến folder checkpoint adapter đã fine-tune
ADAPTER_PATH = "/content/drive/MyDrive/KPDLHLV/qwen3_slm_batch6/checkpoint-3800"

# Tên Base Model gốc (Sửa lại đúng theo yêu cầu Qwen3-0.6B của bạn)
# Lưu ý: Hãy chắc chắn tên này đúng với tên model bạn dùng trong file train
BASE_MODEL_ID = "Qwen/Qwen3-0.6B"

# ================= 2. DỌN DẸP BỘ NHỚ =================
try:
    del model
    del base_model
    del tokenizer
except:
    pass
torch.cuda.empty_cache()
gc.collect()
print("🧹 Đã dọn dẹp bộ nhớ GPU.")

# ================= 3. LOAD MODEL & ADAPTER =================
print(f"📦 Đang tải Base Model: {BASE_MODEL_ID}...")
device = "cuda" if torch.cuda.is_available() else "cpu"

try:
    # Load Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Load Base Model
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        device_map="auto",
        torch_dtype=torch.float16,
        trust_remote_code=True
    )

    # Resize token embedding
    base_model.resize_token_embeddings(len(tokenizer))

    print(f"🔗 Đang ghép Adapter từ: {ADAPTER_PATH}...")
    # Load Adapter
    model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
    model.eval()

    print(f"✅ Đã nạp thành công Model {BASE_MODEL_ID} Fine-tune!")

    # ================= 4. TEST NHANH =================
    test_input = "Context: Bệnh cúm là bệnh truyền nhiễm.\nStatement: Bệnh cúm không lây.\nAnswer:"
    inputs = tokenizer(test_input, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=10)
        print("\n--- Test Output ---")
        print(tokenizer.decode(outputs[0], skip_special_tokens=True))

except OSError as e:
    print(f"\n❌ LỖI: Không tìm thấy model '{BASE_MODEL_ID}' trên Hugging Face hoặc đường dẫn sai.")
    print("👉 Bạn hãy kiểm tra lại chính xác tên Base Model đã dùng lúc train và sửa lại biến BASE_MODEL_ID.")
    print(f"Chi tiết lỗi: {e}")

import torch
import pandas as pd
from tqdm import tqdm

# Đảm bảo bạn đã load model và tokenizer ở các bước trước đó
# Và đã có biến 'example_db' (là biến 'db' cũ chứa dữ liệu train Đúng/Sai)

def generate_enhanced_prompt(user_statement, k_knowledge=1, k_example=2):
    """
    Hàm tạo prompt kết hợp:
    1. Tìm kiến thức từ ViMedAQA để làm Context.
    2. Tìm ví dụ mẫu từ dữ liệu Train để làm Few-shot.
    """

    # BƯỚC 1: Tìm Context từ ViMedAQA
    # Truy vấn bằng chính statement của người dùng
    knowledge_results = knowledge_db.similarity_search(user_statement, k=k_knowledge)

    # Lấy nội dung tốt nhất làm Context
    retrieved_context = ""
    if knowledge_results:
        retrieved_context = knowledge_results[0].page_content
    else:
        retrieved_context = "Không có thông tin bổ sung."

    # BƯỚC 2: Tìm Few-shot Examples từ Dữ liệu Train cũ (biến db cũ)
    # Tìm ví dụ có cấu trúc tương tự
    # Lưu ý: 'db' là biến vector store chứa dữ liệu train đúng/sai bạn đã tạo từ trước
    query_for_example = f"Mệnh đề: {user_statement}"
    example_results = db.similarity_search(query_for_example, k=k_example)

    examples_text = ""
    for doc in example_results:
        ex_ctx = doc.metadata.get('original_context', '')
        ex_stmt = doc.metadata.get('original_statement', '')
        ex_ans = doc.metadata.get('answer', '')
        # Format ví dụ ngắn gọn
        examples_text += f"---\nVí dụ:\nNgữ cảnh: {ex_ctx}\nMệnh đề: {ex_stmt}\n=> Đáp án: {ex_ans}\n"

    # BƯỚC 3: Ghép Prompt
    # Đây là Prompt tối ưu cho model đã fine-tune
    final_prompt = f"""Dưới đây là một số ví dụ mẫu về cách kiểm chứng mệnh đề y khoa:
{examples_text}
---
Dựa vào kiến thức y khoa dưới đây (được trích xuất từ cơ sở dữ liệu ViMedAQA):
{retrieved_context}

Hãy kiểm tra mệnh đề sau:
Mệnh đề: {user_statement}

Hãy phân loại mệnh đề trên là 'Đúng' hoặc 'Sai'.
Câu trả lời:"""

    return final_prompt, retrieved_context

# --- CHẠY THỬ NGHIỆM ---
TEST_FILE = "/content/drive/MyDrive/KPDLHLV/Data/data_test_normalize.csv" # Đổi đường dẫn nếu cần
OUTPUT_FILE = "/content/drive/MyDrive/KPDLHLV/Data/Result_Hybrid_RAG.xlsx"

print("▶️ Bắt đầu chạy Hybrid RAG (ViMedAQA Context + Few-shot)...")

if TEST_FILE.endswith('.csv'):
    df_test = pd.read_csv(TEST_FILE)
else:
    df_test = pd.read_excel(TEST_FILE)

results = []

# Để test nhanh, mình chạy thử 100 câu đầu (bỏ [:100] để chạy hết)
for idx, row in tqdm(df_test.iterrows(), total=len(df_test)):
    stmt = str(row.get('statement', ''))

    # Tạo Prompt kết hợp
    # Lưu ý: Nếu biến vector store cũ của bạn tên là 'db', hàm trên sẽ tự dùng nó.
    rag_prompt, used_context = generate_enhanced_prompt(stmt, k_knowledge=1, k_example=2)

    inputs = tokenizer(rag_prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=5,
            temperature=0.01,
            pad_token_id=tokenizer.pad_token_id
        )

    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer_part = full_response.split("Câu trả lời:")[-1].strip()

    # Logic lấy nhãn
    final_decision = "Sai" # Mặc định an toàn
    if "đúng" in answer_part.lower(): final_decision = "Đúng"
    elif "sai" in answer_part.lower(): final_decision = "Sai"

    results.append({
        "Statement": stmt,
        "Retrieved_Knowledge_ViMedAQA": used_context, # Lưu lại xem nó lấy được kiến thức gì
        "Model_Prediction": final_decision,
        "Raw_Output": answer_part
    })

# Lưu kết quả
pd.DataFrame(results).to_excel(OUTPUT_FILE, index=False)
print(f"✅ Hoàn tất! Kết quả lưu tại: {OUTPUT_FILE}")